/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

/**
 *
 * @author cgpc2
 */
public class VentanaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form VentanaUsuarios
     */
    
    private String user;
    private VentanaConsultas vc;
    
    public VentanaUsuarios() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);    
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelVentanaUsuarios = new java.awt.Panel();
        JLabelUsuario = new javax.swing.JLabel();
        JLabelSesionInicio = new javax.swing.JLabel();
        JLabelPassword = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        JButtonIniciarSesion = new javax.swing.JButton();
        JTextFieldPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Sesión");
        setPreferredSize(new java.awt.Dimension(570, 400));

        JPanelVentanaUsuarios.setBackground(new java.awt.Color(153, 153, 153));

        JLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelUsuario.setText("USUARIO");

        JLabelSesionInicio.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        JLabelSesionInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelSesionInicio.setText("Inicio Sesión");

        JLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelPassword.setText("CONSTRASEÑA");

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "alvaro", "cristobal", "abigail", "ana", "lucia" }));

        JButtonIniciarSesion.setText("CONECTAR");
        JButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonIniciarSesionActionPerformed(evt);
            }
        });

        JTextFieldPassword.setBackground(new java.awt.Color(255, 255, 255));
        JTextFieldPassword.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JPanelVentanaUsuariosLayout = new javax.swing.GroupLayout(JPanelVentanaUsuarios);
        JPanelVentanaUsuarios.setLayout(JPanelVentanaUsuariosLayout);
        JPanelVentanaUsuariosLayout.setHorizontalGroup(
            JPanelVentanaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelVentanaUsuariosLayout.createSequentialGroup()
                .addComponent(JLabelSesionInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JPanelVentanaUsuariosLayout.createSequentialGroup()
                .addGroup(JPanelVentanaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanelVentanaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(JPanelVentanaUsuariosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelVentanaUsuariosLayout.createSequentialGroup()
                            .addGap(222, 222, 222)
                            .addGroup(JPanelVentanaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        JPanelVentanaUsuariosLayout.setVerticalGroup(
            JPanelVentanaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelVentanaUsuariosLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(JLabelSesionInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelVentanaUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelVentanaUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonIniciarSesionActionPerformed
        String password;
        user = (String) jComboBox1.getSelectedItem();
        password = JTextFieldPassword.getText();
        GestorBasesDeDatos.connect(user, password);
        if (GestorBasesDeDatos.isConnected()){
            vc = new VentanaConsultas(this);
            this.setVisible(false);
            vc.setVisible(true);
        }
    }//GEN-LAST:event_JButtonIniciarSesionActionPerformed
 
    private void formWindowClosed(java.awt.event.WindowEvent evt) {                                  
        GestorBasesDeDatos.disconnect();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonIniciarSesion;
    private javax.swing.JLabel JLabelPassword;
    private javax.swing.JLabel JLabelSesionInicio;
    private javax.swing.JLabel JLabelUsuario;
    private java.awt.Panel JPanelVentanaUsuarios;
    private javax.swing.JTextField JTextFieldPassword;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
